[package]
name = "test_vec_bin_op"
version = "0.1.0"
authors = ["Jason Cardinal <jcardinal@dealersocket.com>"]

[dependencies]
num_cpus = "1.0.0"
# rayon = "0.4.2"
rayon = { git = "https://github.com/nikomatsakis/rayon.git" }
# simple_parallel = "0.3.0"
